compatibility_date = "2023-09-07"
compatibility_flags = ["streams_enable_constructors"]

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "race-stack"
database_id = "50fc08fb-3d5c-486c-8d23-26f549baf1a5"
